version: "3.9"

services:
    nestjs:
        build:
            context: .
        command: sleep infinity
        depends_on:
            - mysql
        ports:
            - 3333:3333
        volumes:
            - .:/app
    mysql:
        image: mysql/mysql-server:8.0
        env_file:
            - .env.development
        command: mysqld --default_authentication_plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
        ports:
            - '3306:3306'
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
        driver: local
